### ISSUE TITLE
Showing error 'no matches found:'

### ISSUE THREAD

**Issue by pratikEI** [souravray/gafas#2]
Hello @souravray,
Tried gafas for the mentioned json object got tghis error.. 

zsh: no matches found: inputIds:[d857c31d1438194e204843258fe33bf46dd680d86b2daa34bdd80a24dd50de7a:1]

https://jsoneditoronline.org/?id=8c6314cf067e444097856904e61383aa

gafas {"id":"63b67b40ae538934a9806c58f1f18ff7c36124c3d80464a23287d74f4cc99af6","normalizedTxHash":"63b67b40ae538934a9806c58f1f18ff7c36124c3d80464a23287d74f4cc99af6","date":"2018-07-11T07:49:39.558Z","hex":"020000000001017ade50dd240ad8bd34aa2d6bd880d66df43be38f254348204e1938141dc357d80100000017160014c5efad0f256cc50eea959fc282f61ccc8c695f58feffffff0298d7b918010000001976a9143b8f9f44c22b93e20c2dd2cc428211c556d2855488ac80a4bf070000000017a91494715e7e2d4447e8b4f09ee592c2b7d0c315dd2f8702483045022100c10de029391e040ff299bd9697a3e396a08d56115b51ba83aa92d75c6857dc1e022036ff76455ad9540d2faea2fa621abe7468dc03b0b3cb6a3fd24677777169af0201210293cbef5494d8ec875d6991048c715c897b110b84679d3a8b2e38d732c90d2773cda41400","blockHash":"0000000000009f54d0034f81372030184010e25f2c25d3a4104703ac687bfde1","blockHeight":1352910,"blockPosition":235,"confirmations":8,"fee":168,"feeString":"168","size":168,"inputIds":["d857c31d1438194e204843258fe33bf46dd680d86b2daa34bdd80a24dd50de7a:1"],"inputs":[{"id":"d857c31d1438194e204843258fe33bf46dd680d86b2daa34bdd80a24dd50de7a:1","address":"2MudZ2LBvzAPoVwKRkYrcTYumuiWHhhKJj5","value":4839800000,"valueString":"4839800000","isSegwit":false}],"outputs":[{"id":"63b67b40ae538934a9806c58f1f18ff7c36124c3d80464a23287d74f4cc99af6:0","address":"mkwtDQw6ms1mfK8tXjkj5D2qNbnikr1xjX","value":4709799832,"valueString":"4709799832","isSegwit":false},{"id":"63b67b40ae538934a9806c58f1f18ff7c36124c3d80464a23287d74f4cc99af6:1","address":"2N6n7ohVNYCKrCtvXZ5nXnCTAHY6AriDvGK","value":130000000,"valueString":"130000000","wallet":"5b3b7f5ae277547305ea3348c742f3b9","chain":0,"index":4,"redeemScript":"522103dba5f1a46b9de4688d9a27e2faecc34e49cc857f85428e9df7889dd68466d56821024cfbeefa8a70d1fdf8ce99e4c68e3eb896436d2d2292e324468b32097995c3c5210346b0590512e41a1c613fa61dca116f24e0f5a79345d8b802070acb0a4a3fb56253ae","isSegwit":false}],"entries":[{"address":"2MudZ2LBvzAPoVwKRkYrcTYumuiWHhhKJj5","coinName":"tbtc","inputs":1,"outputs":0,"value":-4839800000,"valueString":"-4839800000"},{"address":"2N6n7ohVNYCKrCtvXZ5nXnCTAHY6AriDvGK","wallet":"5b3b7f5ae277547305ea3348c742f3b9","coinName":"tbtc","inputs":0,"outputs":1,"value":130000000,"valueString":"130000000"},{"address":"mkwtDQw6ms1mfK8tXjkj5D2qNbnikr1xjX","coinName":"tbtc","inputs":0,"outputs":1,"value":4709799832,"valueString":"4709799832"}]}

**Comment by souravray** [comment]
Apparently parsing is working fine 
<img width="1435" alt="screen shot 2018-12-10 at 4 37 35 pm" src="https://user-images.githubusercontent.com/364657/49729027-5241b080-fc9a-11e8-87b8-48ee8194249f.png">
can you please check the version of your Gafas you are using?
